### ISSUE TITLE
Where are the notes ?

### ISSUE THREAD

**Issue by VianneyMI** [afondiel/research-notes#1]
What are you doing Bro ?

**Comment by afondiel** [comment]
They are ranged by branch based on the  type of subject. Switch the branch to see the note

**Comment by VianneyMI** [comment]
You should state it on your readme in the default branch ;)

**Comment by afondiel** [comment]
Thanks for the tip Man! I was actually looking for a way to structure all this at once. I just created a default branch and gathered everything in there. It should be more visible now.
